/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        // Tracelify brand tokens
        background: "#170e2b",
        "inverse-on-surface": "#352b4a",
        "secondary-container": "#c70285",
        "surface-tint": "#cabeff",
        "on-secondary-container": "#ffe0eb",
        tertiary: "#aad636",
        "on-tertiary-fixed-variant": "#3a4d00",
        "on-tertiary-fixed": "#151f00",
        "tertiary-container": "#5f7d00",
        "primary-fixed-dim": "#cabeff",
        outline: "#938ea1",
        "tertiary-fixed": "#c5f251",
        "on-secondary-fixed": "#3d0026",
        "on-primary": "#30009a",
        "on-error-container": "#ffdad6",
        "on-surface": "#eaddff",
        "primary-container": "#7553ff",
        "outline-variant": "#484555",
        "surface-container-high": "#2e2543",
        "tertiary-fixed-dim": "#aad636",
        "secondary-fixed": "#ffd8e7",
        error: "#ffb4ab",
        "surface-container-low": "#1f1633",
        "primary-fixed": "#e6deff",
        "inverse-primary": "#6039e9",
        "surface-container-lowest": "#120825",
        "on-secondary-fixed-variant": "#8b005b",
        "on-error": "#690005",
        "surface-variant": "#39304e",
        "secondary-fixed-dim": "#ffafd3",
        primary: "#cabeff",
        "on-primary-fixed": "#1c0062",
        secondary: "#ffafd3",
        "on-background": "#eaddff",
        "surface-container": "#231a38",
        "on-primary-container": "#fef9ff",
        "surface-bright": "#3e3453",
        "on-secondary": "#620040",
        surface: "#170e2b",
        "on-tertiary-container": "#f4ffd2",
        "on-primary-fixed-variant": "#470cd2",
        "error-container": "#93000a",
        "inverse-surface": "#eaddff",
        "on-surface-variant": "#c9c3d8",
        "surface-dim": "#170e2b",
        "surface-container-highest": "#39304e",
        "on-tertiary": "#273500",
        // shadcn required tokens (mapped to brand)
        border: "#484555",
        input: "#484555",
        ring: "#cabeff",
        muted: {
          DEFAULT: "#1f1633",
          foreground: "#c9c3d8",
        },
        accent: {
          DEFAULT: "#2e2543",
          foreground: "#eaddff",
        },
        popover: {
          DEFAULT: "#231a38",
          foreground: "#eaddff",
        },
        card: {
          DEFAULT: "#1f1633",
          foreground: "#eaddff",
        },
        destructive: {
          DEFAULT: "#93000a",
          foreground: "#ffdad6",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: 0, transform: "translateX(-20px)" },
          "100%": { opacity: 1, transform: "translateX(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        glow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(117, 83, 255, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(117, 83, 255, 0.6)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "slide-in-left": "slide-in-left 0.6s ease-out forwards",
        float: "float 3s ease-in-out infinite",
        glow: "glow 2s ease-in-out infinite",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [],
}
